"""
Candidate generation and matching module for cross-revision characteristic matching.

This module implements the core matching logic that finds potential Rev B candidates 
for each Rev A characteristic anchor. It uses spatial transformation to predict where
characteristics should appear in Rev B, then ranks candidates using multi-component
scoring that combines location, semantic similarity, and spatial context.

The matching process is critical for maintaining characteristic identity across 
drawing revisions, even when layout changes significantly.
"""

from typing import List, Tuple, Optional
from dataclasses import dataclass
import math
import re
import numpy as np
import cv2

from delta_preservation.reconcile.anchors import Anchor
from delta_preservation.io.pdf import TextSpan
from delta_preservation.vision.bbox_utils import union_bbox
from delta_preservation.reconcile.normalize import parse_requirement
from delta_preservation.reconcile.semantic_compare import compare_semantic_callouts
from delta_preservation.types import SemanticCallout
from delta_preservation.vision.alignment import Transform


@dataclass(frozen=True)
class GroupedSpan:
    """Synthetic text span assembled from nearby PDF spans that together form one callout."""

    text: str
    bbox_pdf: Tuple[float, float, float, float]
    font_size: float
    block_id: int
    line_id: int
    span_id: int
    source_spans: List[TextSpan]


@dataclass
class Candidate:
    """
    Represents a potential Rev B match for a Rev A characteristic anchor.

    Candidates are generated by spatial search around the predicted Rev B location
    and ranked using multi-component scoring. Each candidate represents a text span
    in Rev B that could potentially be the same characteristic as the Rev A anchor.

    Attributes:
        span: The Rev B text span containing potential requirement text
        total_score: Combined weighted score (0-1) indicating match confidence
        location_score: Distance-based proximity score (0-1, higher = closer)
        text_score: Semantic similarity score (0-1, higher = more similar content)
        context_score: Spatial context similarity score (0-1, higher = similar neighborhood)
        reasons: Human-readable explanations of score components for debugging/review
        from_global_fallback: True when this candidate was found only via the page-wide
            global fallback (no viable normal-radius candidate existed).  Used by the
            shared-span fallback in assign_matches() to exclude truly-removed anchors
            from reusing already-assigned spans.

    Notes:
        - Total score combines all component scores with domain-specific weights
        - Reasons provide transparency for human review of matching decisions
        - Scores are normalized to [0,1] range for consistent interpretation
    """
    span: TextSpan
    total_score: float
    location_score: float
    text_score: float
    context_score: float
    reasons: List[str]
    from_global_fallback: bool = False
    source_span_keys: Optional[List[tuple]] = None


@dataclass
class Match:
    """
    Represents a confirmed assignment of a Rev A characteristic to a Rev B span.
    
    A Match is the result of the candidate ranking and assignment process, representing
    the system's best guess for where a Rev A characteristic appears in Rev B. This
    forms the basis for delta classification (unchanged/changed/removed).
    
    Attributes:
        char_no: Characteristic number from Rev A anchor (e.g., 1, 2, 17)
        candidate: The selected Candidate object containing the Rev B span and scores
        pred_center_b: Predicted center coordinates in Rev B (x, y) from spatial transform
        
    Notes:
        - Only one Match per char_no (enforced by assignment algorithm)
        - pred_center_b shows where the spatial transform predicted the characteristic
        - candidate.span contains the actual Rev B text that was matched
    """
    char_no: int
    candidate: Candidate
    pred_center_b: Optional[Tuple[float, float]] = None


def _span_key(span: TextSpan | GroupedSpan) -> tuple:
    return (
        span.block_id,
        span.line_id,
        span.span_id,
        span.bbox_pdf,
    )


_GDT_CONTROL_CHARS = frozenset("⌖⌒⟂⊙⌓⏥∥∠↧")
_GDT_COMPANION_CHARS = _GDT_CONTROL_CHARS | frozenset("Ø⌀RⓂⓁⓅ")
_GDT_MODIFIER_TOKENS = frozenset({"M", "L", "P", "MMC", "LMC", "RFS"})


def _normalize_span_text(text: str) -> str:
    return " ".join(text.strip().upper().split())


def _span_has_numeric_payload(text: str) -> bool:
    return bool(re.search(r"\d|[+\-±]", text))


def _looks_like_gdt_fragment(text: str) -> bool:
    normalized = _normalize_span_text(text)
    if not normalized:
        return False
    if any(ch in text for ch in _GDT_COMPANION_CHARS):
        return True
    if normalized in _GDT_MODIFIER_TOKENS:
        return True
    if re.fullmatch(r"[A-HJ-NP-Z]", normalized):
        return True
    return False


def _horizontal_gap(a: TextSpan, b: TextSpan) -> float:
    ax0, _ay0, ax1, _ay1 = a.bbox_pdf
    bx0, _by0, bx1, _by1 = b.bbox_pdf
    if bx0 > ax1:
        return bx0 - ax1
    if ax0 > bx1:
        return ax0 - bx1
    return 0.0


def _spans_are_companions(base: TextSpan, other: TextSpan) -> bool:
    bx0, by0, bx1, by1 = base.bbox_pdf
    ox0, oy0, ox1, oy1 = other.bbox_pdf
    bcx = (bx0 + bx1) / 2
    bcy = (by0 + by1) / 2
    ocx = (ox0 + ox1) / 2
    ocy = (oy0 + oy1) / 2
    base_h = max(1.0, by1 - by0)
    other_h = max(1.0, oy1 - oy0)

    same_row = abs(ocy - bcy) <= max(10.0, 0.75 * max(base_h, other_h))
    horiz_gap = _horizontal_gap(base, other)
    center_dx = abs(ocx - bcx)
    center_dy = abs(ocy - bcy)
    pair_is_gdt = _looks_like_gdt_fragment(base.text) or _looks_like_gdt_fragment(other.text)
    either_has_numeric_payload = _span_has_numeric_payload(base.text) or _span_has_numeric_payload(other.text)

    close_horiz_limit = 28.0 if pair_is_gdt else 20.0
    center_dx_limit = 32.0 if pair_is_gdt else 28.0
    stacked_dx_limit = 18.0 if pair_is_gdt else 14.0
    stacked_dy_limit = 18.0 if pair_is_gdt else 14.0

    if same_row and (horiz_gap <= close_horiz_limit or center_dx <= center_dx_limit):
        if pair_is_gdt or either_has_numeric_payload:
            return True

    if (
        abs(ocx - bcx) <= stacked_dx_limit
        and 0.0 < center_dy <= stacked_dy_limit
        and (pair_is_gdt or either_has_numeric_payload)
    ):
        return True

    return False


def _group_candidate_spans(seed_span: TextSpan, all_spans: List[TextSpan]) -> GroupedSpan:
    """Merge nearby companion spans into one synthetic span for matching.

    Handles common drawing patterns:
    - diameter/radius symbol split from numeric text
    - stacked limits/tolerances above and below the nominal
    - GD&T symbol/value/datum fragments on the same row

    Grouping walks companion relationships to a fixed point so multi-hop local
    chains (e.g. symbol → tolerance → modifier → datum) stay intact without
    weakening assign_matches() ownership heuristics.
    """
    included: List[TextSpan] = [seed_span]
    seen = {_span_key(seed_span)}
    queue: List[TextSpan] = [seed_span]
    bbox = seed_span.bbox_pdf

    while queue:
        current = queue.pop(0)
        for other in all_spans:
            if other is current:
                continue
            other_key = _span_key(other)
            if other_key in seen:
                continue
            if not _spans_are_companions(current, other):
                continue
            included.append(other)
            seen.add(other_key)
            queue.append(other)
            bbox = union_bbox(bbox, other.bbox_pdf)

    unique_spans = sorted(
        included,
        key=lambda s: (
            (s.bbox_pdf[1] + s.bbox_pdf[3]) / 2,
            s.bbox_pdf[0],
            s.block_id,
            s.line_id,
            s.span_id,
        ),
    )
    text = " ".join(s.text.strip() for s in unique_spans if s.text.strip())
    avg_font = sum(s.font_size for s in unique_spans) / max(1, len(unique_spans))

    return GroupedSpan(
        text=text,
        bbox_pdf=bbox,
        font_size=avg_font,
        block_id=seed_span.block_id,
        line_id=seed_span.line_id,
        span_id=seed_span.span_id,
        source_spans=unique_spans,
    )


_TITLE_BLOCK_EXACT = frozenset({
    "DATE", "TITLE", "NAME", "DRAWN", "CHECKED", "DESIGNED", "APPROVED",
    "REV", "REV.", "REVISION", "MATERIAL", "MATERIALS", "FINISH",
    "SCALE", "SHEET", "SIZE", "DWG NO.", "DWG NO", "WEIGHT",
    "THIRD ANGLE PROJECTION", "FIRST ANGLE PROJECTION",
    "DO NOT SCALE DRAWING", "DO NOT SCALE",
    "BREAK ALL SHARP EDGES AND", "BREAK ALL SHARP EDGES", "REMOVE BURRS",
    "DIMENSIONS ARE IN INCHES", "DIMENSIONS ARE IN MM",
    "DIMENSIONS ARE IN MILLIMETERS",
    "SURFACE FINISH", "PROPRIETARY", "CONFIDENTIAL",
    "UNLESS OTHERWISE SPECIFIED", "UNLESS OTHERWISE SPECIFIED,",
    "INTERPRET DRAWING PER", "INTERPRET DIMENSIONS PER",
    "THIRD ANGLE", "DRAWING NO", "DRAWING NO.",
    "MACHINING",
})

_TITLE_BLOCK_CONTAINS = (
    "UNLESS OTHERWISE SPECIFIED",
    "INTERPRET DIMENSIONING AND TOLERANCING",
    "INTERPRET DRAWING PER",
    "DO NOT SCALE",
    "THIRD ANGLE",
    "FIRST ANGLE",
    "BREAK ALL SHARP",
    "REMOVE BURRS",
    "DIMENSIONS ARE IN",
)

_TITLE_BLOCK_PATTERNS = [
    re.compile(r"^\s*\.X+\s*=\s*"),           # .X = ±.050, .XX = ±.020
    re.compile(r"^\s*\d+\s+of\s+\d+\s*$"),    # "1 of 1", "2 of 3"
    re.compile(r"^(ANGULAR|FRACTIONAL)\s*="),  # ANGULAR = ±0.3°
    re.compile(r"^\d+\.\s+(QTY|ALL DIMS|MATL|FINISH|BREAK|INTERPRET)"),  # Notes block items
]


def _is_boilerplate_candidate_text(text: str) -> bool:
    """Return True for general tolerance/title-block boilerplate text.

    These spans often contain engineering numerics/symbols (e.g. "ANGULAR = ±0.3°")
    but are not characteristic annotations and should never be matched.
    """
    upper = " ".join(text.strip().upper().split())
    if not upper:
        return False
    if upper in _TITLE_BLOCK_EXACT:
        return True
    for phrase in _TITLE_BLOCK_CONTAINS:
        if phrase in upper:
            return True
    for pat in _TITLE_BLOCK_PATTERNS:
        if pat.match(upper):
            return True
    return False


def _span_is_excluded_for_matching(
    span: TextSpan,
    *,
    page_width_est: float,
    page_height_est: float,
) -> bool:
    """Return True when a span lies in a non-annotation boilerplate region."""
    sx0, sy0, sx1, sy1 = span.bbox_pdf
    span_cx = (sx0 + sx1) / 2
    span_cy = (sy0 + sy1) / 2

    if span_cx > page_width_est * 0.70 and span_cy > page_height_est * 0.85:
        return True  # Title block
    if span_cx > page_width_est * 0.75 and span_cy < page_height_est * 0.15:
        return True  # Revision table
    if page_height_est * 0.78 <= span_cy <= page_height_est * 0.92 and page_width_est * 0.25 <= span_cx <= page_width_est * 0.72:
        if _is_boilerplate_candidate_text(span.text):
            return True  # General tolerance/defaults block near bottom-centre
    if _is_boilerplate_candidate_text(span.text):
        return True
    return False


def generate_candidates(
    anchor: Anchor,
    revB_spans: List[TextSpan],
    transform: Transform | List[Transform],
    top_k: int = 5,
    anchor_semantic_callout: Optional[SemanticCallout] = None,
    revB_semantic_callouts_by_span_key: Optional[dict[tuple, SemanticCallout]] = None,
) -> List[Candidate]:
    """
    Generate and rank candidate matches for a Rev A anchor in Rev B coordinate space.
    
    This function implements the core characteristic matching algorithm:
    1. Apply homography transform to predict where anchor should appear in Rev B
    2. Search within a fixed radius for potential candidate text spans
    3. Score each candidate using location, semantic, and context similarity
    4. Return the top-K highest scoring candidates for assignment consideration
    
    The spatial transform handles layout changes between revisions, while multi-component
    scoring ensures robust matching even when text formatting or positioning varies.
    
    Args:
        anchor: Rev A anchor containing requirement text and spatial information
        revB_spans: Complete list of text spans extracted from Rev B PDF
        transform: Homography transformation matrix from Rev A to Rev B coordinates
        top_k: Maximum number of top-scoring candidates to return (default: 5)
        
    Returns:
        List of Candidate objects sorted by total_score in descending order.
        List may be shorter than top_k if fewer candidates found within search radius.
        
    Notes:
        - Uses 144 PDF point (~2 inch) search radius to handle layout variations
        - Prioritizes requirement text bbox over balloon center for spatial prediction
        - Handles cases where anchor has no requirement text bbox (uses balloon fallback)
        - All candidates include detailed scoring breakdown for transparency
    """
    # Define search radius to handle layout variations between revisions.
    # 288 PDF points ≈ 4 inches at 72 DPI.
    # A generous radius is needed because:
    # 1. Text-span alignment computes the dominant translation (median of shifted pairs).
    # 2. Drawing revisions may have multiple view groups shifting by different amounts
    #    (e.g., main view +362 pts, side view +212 pts when dominant is +362).
    # 3. Features in the secondary shift group land ~150 pts off from predicted.
    # 4. Features whose anchor has req_bbox=None (balloon-only) have ~30 pt extra error
    #    compared to annotation-centered predictions.
    # 5. Incorrect candidates are still rejected by text scoring and the primary-
    #    mismatch penalty — false matches from far-away wrong spans get suppressed.
    SEARCH_RADIUS = 288.0
    
    # Determine the Rev A coordinate to transform (prefer requirement text over balloon,
    # and use zone bbox center as a last resort when both are unavailable).
    if anchor.req_bbox is not None:
        x0, y0, x1, y1 = anchor.req_bbox
        center_a = np.array([[(x0 + x1) / 2, (y0 + y1) / 2]], dtype=np.float32)
    elif anchor.zone_bbox is not None:
        # Zone center provides a grid-level prediction for the characteristic
        # location when the exact annotation bbox could not be found.
        zx0, zy0, zx1, zy1 = anchor.zone_bbox
        center_a = np.array([[(zx0 + zx1) / 2, (zy0 + zy1) / 2]], dtype=np.float32)
    else:
        # Fall back to balloon center when neither annotation nor zone is known
        center_a = np.array([[(anchor.balloon_bbox[0] + anchor.balloon_bbox[2]) / 2,
                             (anchor.balloon_bbox[1] + anchor.balloon_bbox[3]) / 2]], dtype=np.float32)

    # For notes-type characteristics, skip the homography: drawing notes blocks
    # are static and do not move between revisions even when annotation content shifts.
    # Applying the content-shift transform to a static element produces a wrong prediction.
    anchor_fp = parse_requirement(anchor.requirement_raw)
    is_notes_anchor = (
        anchor_fp.pattern_class == "note"
        or "NOTES" in anchor.requirement_raw.upper()
    )

    center_a = center_a.reshape(-1, 1, 2)
    transforms = transform if isinstance(transform, list) else [transform]
    if is_notes_anchor:
        # Use Rev A location directly (identity transform for static notes block)
        predicted_centers = [(float(center_a[0, 0, 0]), float(center_a[0, 0, 1]))]
    else:
        predicted_centers = []
        for tf in transforms:
            center_b = cv2.perspectiveTransform(center_a, tf.H)[0][0]
            pred_x, pred_y = float(center_b[0]), float(center_b[1])
            if not any(abs(pred_x - ex) <= 5.0 and abs(pred_y - ey) <= 5.0 for ex, ey in predicted_centers):
                predicted_centers.append((pred_x, pred_y))
    
    # Estimate page dimensions from spans for exclusion-zone computations.
    # These mirror the zones used by detect_added_characteristics so that
    # title-block text (dates, revision labels, part numbers) is never selected
    # as a candidate match — it would otherwise score well on location for
    # non-numeric anchors (e.g., "THRU") because both have no numeric content.
    # Use a floor of half a letter page (306×396 pt) so that the exclusion zones
    # remain meaningful even when revB_spans contains only a few spans (e.g., in
    # unit tests).  Real drawings always have wider/taller extent than the floor.
    if revB_spans:
        page_width_est = max(max(s.bbox_pdf[2] for s in revB_spans), 612.0)
        page_height_est = max(max(s.bbox_pdf[3] for s in revB_spans), 792.0)
    else:
        page_width_est = 792.0
        page_height_est = 612.0

    def _nearest_predicted_distance(span_cx: float, span_cy: float) -> float:
        return min(
            math.sqrt((span_cx - pred_x) ** 2 + (span_cy - pred_y) ** 2)
            for pred_x, pred_y in predicted_centers
        )

    # Build candidate pool from spans within search radius.
    # Pre-filter to reduce computational cost of detailed scoring.
    # For notes-type anchors, restrict candidates to spans that look like notes headers
    # (contain "NOTE" or "NOTES") — note item number spans (e.g., "3.", "2.") are too
    # common and score higher on location than the actual header, causing wrong matches.
    candidate_pool = []
    seen_group_keys = set()
    for span in revB_spans:
        sx0, sy0, sx1, sy1 = span.bbox_pdf
        span_cx = (sx0 + sx1) / 2
        span_cy = (sy0 + sy1) / 2
        dist = _nearest_predicted_distance(span_cx, span_cy)

        if dist <= SEARCH_RADIUS:
            if _span_is_excluded_for_matching(
                span,
                page_width_est=page_width_est,
                page_height_est=page_height_est,
            ):
                continue

            if is_notes_anchor:
                # Only include spans that are actual notes headers
                span_upper = span.text.strip().upper()
                if "NOTE" not in span_upper and "DRAWING" not in span_upper:
                    continue

            grouped = _group_candidate_spans(span, revB_spans)
            gkey = (_span_key(grouped), tuple(_span_key(s) for s in grouped.source_spans))
            if gkey in seen_group_keys:
                continue
            seen_group_keys.add(gkey)
            # Post-grouping boilerplate check: the grouped text may reveal
            # notes-block items ("1. QTY: 2") that individual spans don't.
            if _is_boilerplate_candidate_text(grouped.text):
                continue
            candidate_pool.append((grouped, dist, span_cx, span_cy))
    
    # Apply detailed multi-component scoring to each candidate
    # This is the most computationally intensive part but crucial for accuracy
    candidates = []
    for span, dist, cx, cy in candidate_pool:
        candidate = score_candidate(
            anchor, span, dist, SEARCH_RADIUS,
            revB_spans, cx, cy,
            anchor_semantic_callout=anchor_semantic_callout,
            span_semantic_callout=(
                revB_semantic_callouts_by_span_key.get((span.block_id, span.line_id, span.span_id, span.bbox_pdf))
                if revB_semantic_callouts_by_span_key is not None
                else None
            ),
        )
        candidates.append(candidate)
    
    # Return top-K candidates sorted by total score (best matches first)
    # This ranking determines which candidates get considered for assignment
    candidates.sort(key=lambda c: c.total_score, reverse=True)
    candidates = candidates[:top_k]

    # --- Global text-based fallback ---
    # When no candidates were found in the normal search radius, OR all found
    # candidates score below the assignment threshold (MIN_MATCH_SCORE), the
    # annotation may have moved far beyond the window.  Fall back to a page-wide
    # search so that text / semantic similarity is the primary discriminator and
    # spatial proximity acts only as a weak tiebreaker between equal candidates.
    no_viable_candidate = not any(c.total_score >= 0.12 for c in candidates)
    if no_viable_candidate and not is_notes_anchor:
        GLOBAL_RADIUS = 2000.0  # ~28-inch diagonal; larger than any standard A-size sheet
        global_pool = []
        seen_group_keys = set()
        for span in revB_spans:
            sx0, sy0, sx1, sy1 = span.bbox_pdf
            span_cx = (sx0 + sx1) / 2
            span_cy = (sy0 + sy1) / 2
            dist = _nearest_predicted_distance(span_cx, span_cy)
            if _span_is_excluded_for_matching(
                span,
                page_width_est=page_width_est,
                page_height_est=page_height_est,
            ):
                continue
            grouped = _group_candidate_spans(span, revB_spans)
            gkey = (_span_key(grouped), tuple(_span_key(s) for s in grouped.source_spans))
            if gkey in seen_group_keys:
                continue
            seen_group_keys.add(gkey)
            global_pool.append((grouped, dist, span_cx, span_cy))

        global_candidates = []
        for span, dist, cx, cy in global_pool:
            candidate = score_candidate(
                anchor, span, dist, GLOBAL_RADIUS,
                revB_spans, cx, cy,
                anchor_semantic_callout=anchor_semantic_callout,
                span_semantic_callout=(
                    revB_semantic_callouts_by_span_key.get(
                        (span.block_id, span.line_id, span.span_id, span.bbox_pdf)
                    )
                    if revB_semantic_callouts_by_span_key is not None
                    else None
                ),
            )
            semantic_mode = None
            if anchor_semantic_callout is not None or (
                revB_semantic_callouts_by_span_key is not None and hasattr(span, "source_spans")
            ):
                pass
            carry_global = candidate.total_score >= 0.10 and (
                candidate.text_score >= 0.20 or any("semantic weld" in r or "semantic GD&T" in r or "semantic surface finish" in r or "semantic fit" in r for r in candidate.reasons)
            )
            if carry_global:
                candidate.from_global_fallback = True
                global_candidates.append(candidate)

        global_candidates.sort(key=lambda c: c.total_score, reverse=True)
        candidates = global_candidates[:top_k]

    return candidates


def score_candidate(
    anchor: Anchor,
    span: TextSpan,
    dist: float,
    radius: float,
    all_spans: List[TextSpan],
    span_cx: float,
    span_cy: float,
    anchor_semantic_callout: Optional[SemanticCallout] = None,
    span_semantic_callout: Optional[SemanticCallout] = None,
) -> Candidate:
    """
    Compute multi-component similarity score for a candidate Rev B span.
    
    This function implements the core matching intelligence by analyzing three
    complementary similarity signals:
    1. Location: Spatial proximity to the predicted Rev B location
    2. Text: Semantic similarity of requirement content (symbols, numbers, patterns)
    3. Context: Similarity of nearby text spans (spatial neighborhood fingerprint)
    
    The scoring emphasizes numeric value matching as the primary discriminator,
    since dimension values are the most reliable identifier of engineering
    characteristics. Location provides spatial validation, while context helps
    disambiguate when multiple similar annotations exist.
    
    Args:
        anchor: Rev A anchor containing original requirement text and context
        span: Candidate Rev B text span being evaluated for matching
        dist: Distance in PDF points from span center to predicted Rev B center
        radius: Search radius used to normalize distance scores
        all_spans: Complete list of Rev B spans for context analysis
        span_cx: X-coordinate of candidate span center (for context search)
        span_cy: Y-coordinate of candidate span center (for context search)
        
    Returns:
        Candidate object with detailed scoring breakdown and human-readable
        explanations for transparency in matching decisions.
        
    Notes:
        - Numeric matching receives highest weight (50%) in final score
        - Primary value mismatches incur significant penalties
        - Context similarity uses Jaccard index of neighboring text tokens
        - All component scores normalized to [0,1] for consistent weighting
    """
    reasons = []
    
    # (1) Location score - distance-based, normalized to [0, 1]
    location_score = 1.0 - min(dist / radius, 1.0)
    if location_score > 0:
        dist_mm = dist * 25.4 / 72.0  # Convert points to mm
        reasons.append(f"within {dist_mm:.1f} mm of predicted location")
    
    # (2) Text score - semantic matching using parsed requirement fingerprints
    # Parse both texts to extract symbols, numbers, patterns for structured comparison
    anchor_fp = parse_requirement(anchor.requirement_raw)
    span_fp = parse_requirement(span.text)

    semantic_score = 0.0
    semantic_result = None
    if anchor_semantic_callout is not None or span_semantic_callout is not None:
        semantic_result = compare_semantic_callouts(anchor_semantic_callout, span_semantic_callout)
        reasons.extend(semantic_result.reason_fragments)
        if semantic_result.mode == "semantic":
            semantic_score = 1.0 if semantic_result.equal else 0.0
        elif semantic_result.mode == "incompatible":
            semantic_score = 0.0
    
    # Compare engineering symbols (e.g., Ø for diameter, R for radius, ± for tolerance)
    anchor_symbols = set(anchor_fp.symbol_tokens)
    span_symbols = set(span_fp.symbol_tokens)
    symbol_match = len(anchor_symbols & span_symbols) / max(len(anchor_symbols), 1) if anchor_symbols else 0.0
    
    # Compare count patterns (e.g., 2X, 4X, 6X)
    anchor_counts = set(anchor_fp.count_tokens)
    span_counts = set(span_fp.count_tokens)
    has_count_pattern = bool(anchor_counts and span_counts)
    count_exact_match = anchor_counts == span_counts if anchor_counts else True
    
    # Compare numeric values - THIS IS THE KEY DISCRIMINATOR
    # Extract the primary numeric value (usually the dimension value, not tolerance)
    anchor_numerics = set(val for val, _ in anchor_fp.numeric_tokens)
    span_numerics = set(val for val, _ in span_fp.numeric_tokens)
    
    # Identify the "primary" numeric value (largest value, likely the dimension)
    anchor_primary = max(anchor_numerics) if anchor_numerics else None
    span_primary = max(span_numerics) if span_numerics else None
    
    # Compute numeric overlap
    if anchor_numerics:
        numeric_overlap = len(anchor_numerics & span_numerics) / len(anchor_numerics)
    else:
        numeric_overlap = 1.0 if not span_numerics else 0.0
    
    # Check if primary value is present in the span's numeric set.
    # Using set membership (rather than max-equality) correctly handles multi-value
    # spans such as "10 x 90°" where the anchor primary (10) is present even though
    # the span's overall maximum (90) differs.
    primary_value_match = (
        anchor_primary is not None and
        anchor_primary in span_numerics
    )
    
    # Strong penalty if primary values exist but don't match.
    # This prevents matching "110" to "120" even if they're close in location.
    #
    # However, engineering drawing PDFs often express tolerances in "limits form":
    # instead of "0.150 ± 0.010" the drawing shows ".160" (upper) and ".140" (lower)
    # as stacked numbers.  In this case anchor_primary=0.15 and span_primary=0.16 —
    # they differ by 6.7%, which is within the tolerance band of the characteristic.
    # We apply a reduced penalty when the primary values are "close" (within 20%),
    # recognising that the span might be the upper or lower tolerance limit.
    #
    # Also penalise spans with NO numeric content when the anchor expects numerics,
    # BUT ONLY when the anchor is a dimension-type requirement (not notes/text blocks).
    # This prevents non-numeric title-block text from outscoring the correct annotation
    # when the predicted location accidentally falls near the title block.
    # Notes-type anchors are excluded because their header span ("DRAWING NOTES:") is
    # intentionally non-numeric.
    is_notes_anchor = anchor_fp.pattern_class == "note" or "NOTES" in anchor.requirement_raw.upper()
    primary_mismatch_penalty = 0.0
    if anchor_primary is not None and not is_notes_anchor:
        if not span_numerics:
            # Anchor expects numeric content but this span has none — penalise
            primary_mismatch_penalty = 0.35
            reasons.append(f"anchor expects numeric {anchor_primary} but span has no numerics")
        elif anchor_primary not in span_numerics:
            # Check whether the difference could be explained by tolerance notation.
            # If span_primary is within 20% of anchor_primary, apply a reduced penalty.
            if span_primary is not None and anchor_primary != 0:
                relative_diff = abs(anchor_primary - span_primary) / abs(anchor_primary)
                if relative_diff <= 0.20:
                    # Likely limits-form notation or a changed dimension close to anchor.
                    # Apply a small penalty that doesn't totally suppress the location score.
                    primary_mismatch_penalty = 0.05
                    reasons.append(f"primary value {anchor_primary} close to span {span_primary} (±{relative_diff*100:.0f}%)")
                else:
                    # The anchor's primary value is NOT in the span — strong penalty
                    primary_mismatch_penalty = 0.4
                    reasons.append(f"primary value {anchor_primary} not found in span")
            else:
                primary_mismatch_penalty = 0.4
                reasons.append(f"primary value {anchor_primary} not found in span")
    
    # Compare pattern class (hole, dimension, note, etc.)
    class_match = 1.0 if anchor_fp.pattern_class == span_fp.pattern_class else 0.0

    # Weighted combination for text score
    # Numeric matching remains dominant for non-semantic items, while semantic equality
    # can strongly reinforce supported parsed families without suppressing fallback paths.
    text_score = (
        0.15 * symbol_match +
        0.10 * (1.0 if has_count_pattern else 0.0) +
        0.35 * numeric_overlap +
        0.10 * class_match +
        0.10 * (1.0 if primary_value_match else 0.0) +
        0.20 * semantic_score
    )
    
    matched_parts = []
    if symbol_match > 0:
        matched_parts.append(f"symbols: {anchor_symbols & span_symbols}")
    if has_count_pattern:
        matched_parts.append(f"counts: {anchor_counts} vs {span_counts}")
    if numeric_overlap > 0:
        matched_parts.append(f"numerics: {int(numeric_overlap*100)}%")
    if primary_value_match:
        matched_parts.append(f"primary={anchor_primary}")
    if semantic_result is not None:
        if semantic_result.mode == "semantic" and semantic_result.equal:
            matched_parts.append(f"semantic {semantic_result.family}: equal")
        elif semantic_result.mode == "semantic" and semantic_result.equal is False:
            matched_parts.append(f"semantic {semantic_result.family}: changed")
        elif semantic_result.mode == "fallback":
            matched_parts.append("semantic: fallback")
        elif semantic_result.mode == "incompatible":
            matched_parts.append("semantic: incompatible")

    if matched_parts:
        reasons.append(f"matched: {', '.join(matched_parts)}")
    
    # (3) Context score - Jaccard of neighboring spans
    CONTEXT_WINDOW = 50.0  # Points
    
    # Get anchor context tokens
    anchor_context_tokens = set()
    for ctx_span in anchor.local_context:
        ctx_parsed = parse_requirement(ctx_span.text)
        anchor_context_tokens.update(ctx_parsed.norm_text.split())
    
    # Get candidate context tokens from nearby Rev B spans.
    # Use spatial proximity only — do NOT filter by block_id because each annotation
    # in an engineering drawing PDF is typically its own block, so the block_id filter
    # would exclude all neighboring spans and make context score always 0.
    candidate_context_tokens = set()
    for other_span in all_spans:
        ox0, oy0, ox1, oy1 = other_span.bbox_pdf
        other_cx = (ox0 + ox1) / 2
        other_cy = (oy0 + oy1) / 2
        other_dist = math.sqrt((other_cx - span_cx)**2 + (other_cy - span_cy)**2)

        if other_dist <= CONTEXT_WINDOW and other_dist > 0:
            other_parsed = parse_requirement(other_span.text)
            candidate_context_tokens.update(other_parsed.norm_text.split())
    
    # Jaccard similarity
    if anchor_context_tokens or candidate_context_tokens:
        intersection = len(anchor_context_tokens & candidate_context_tokens)
        union = len(anchor_context_tokens | candidate_context_tokens)
        context_score = intersection / union if union > 0 else 0.0
        if context_score > 0:
            reasons.append(f"context similarity: {context_score:.2f}")
    else:
        context_score = 0.0
    
    # Combine scores with rebalanced weights
    # Text/numeric matching is now more important than location
    LOCATION_WEIGHT = 0.35
    TEXT_WEIGHT = 0.50
    CONTEXT_WEIGHT = 0.15
    
    total_score = (
        LOCATION_WEIGHT * location_score +
        TEXT_WEIGHT * text_score +
        CONTEXT_WEIGHT * context_score -
        primary_mismatch_penalty  # Apply penalty for wrong primary value
    )
    
    # Ensure score doesn't go negative
    total_score = max(0.0, total_score)
    
    return Candidate(
        span=span,
        total_score=total_score,
        location_score=location_score,
        text_score=text_score,
        context_score=context_score,
        reasons=reasons,
        source_span_keys=[_span_key(s) for s in getattr(span, "source_spans", [])] or [_span_key(span)],
    )


def assign_matches(
    anchors: List[Anchor],
    candidates_by_anchor: dict[int, List[Candidate]]
) -> dict[int, Match]:
    """Greedily assign anchors to Rev B spans using a global matching strategy.

    This function implements a greedy bipartite matching algorithm that ensures:
    1. Each characteristic (char_no) is assigned at most once
    2. Each Rev B span is matched to at most one characteristic (with shared-span exception)

    The algorithm flattens all candidate edges, sorts by score, and greedily
    accepts edges that don't conflict with previous assignments.

    Shared-span fallback: Engineering drawings sometimes encode multiple characteristics
    in a single callout (e.g., "10 x 90°" encodes both depth=10 and angle=90°).
    After the main greedy pass, any unmatched anchor whose primary value IS present
    in an already-used span is allowed to share that span rather than being classified
    as "removed".

    Args:
        anchors: List of Rev A anchors with characteristic numbers
        candidates_by_anchor: Dict mapping char_no to list of candidates

    Returns:
        Dict mapping assigned char_no to its Match object
    """
    # Build anchor lookup by char_no for the shared-span fallback
    anchor_by_char: dict[int, Anchor] = {a.char_no: a for a in anchors}

    # Build list of all edges: (total_score, char_no, span_key, candidate)
    edges = []
    for anchor in anchors:
        char_no = anchor.char_no
        candidates = candidates_by_anchor.get(char_no, [])

        for candidate in candidates:
            # Create unique span key using TextSpan attributes
            span = candidate.span
            span_key = (
                span.block_id,
                span.line_id,
                span.span_id,
                span.bbox_pdf
            )

            edges.append((
                candidate.total_score,
                char_no,
                span_key,
                candidate
            ))

    # Sort edges by total_score descending
    edges.sort(key=lambda e: e[0], reverse=True)

    # Pre-compute which span keys have at least one non-global-fallback claimant.
    # A global-fallback-only edge must not steal a span that a local candidate
    # already claims, regardless of score order.  This is the Part 3-style
    # wrong-copy guard: a removed anchor (whose candidates are all from the
    # page-wide fallback pool) cannot displace a surviving anchor that has a
    # legitimate local candidate for the same annotation span.
    span_keys_with_local_claimant: set = set()
    for _score, _char_no, _span_key, _cand in edges:
        if not _cand.from_global_fallback:
            span_keys_with_local_claimant.add(_span_key)

    # For direct same-source-span collisions, prefer the anchor with the strongest
    # local ownership signal rather than whichever edge happens to have the highest
    # total score.  This is intentionally scoped to identical grouped source-span
    # sets so the later shared-span fallback still handles genuine combined
    # annotations (e.g. one callout encoding two different characteristics).
    source_span_claims: dict[tuple, list[tuple[int, Candidate]]] = {}
    for _score, _char_no, _span_key, _cand in edges:
        source_key = tuple(sorted(_cand.source_span_keys or [_span_key]))
        source_span_claims.setdefault(source_key, []).append((_char_no, _cand))

    preferred_owner_by_source_span_keys: dict[tuple, int] = {}
    for source_key, claims in source_span_claims.items():
        claimant_chars = {claim_char_no for claim_char_no, _claim_cand in claims}
        if len(claimant_chars) <= 1:
            continue
        owner_char_no, _owner_candidate = max(
            claims,
            key=lambda item: (
                not item[1].from_global_fallback,
                item[1].location_score,
                item[1].total_score,
                -item[0],
            ),
        )
        preferred_owner_by_source_span_keys[source_key] = owner_char_no

    # Greedy assignment
    assigned_chars = set()
    used_spans = set()
    used_source_span_keys = set()
    matches = {}

    # Minimum total score threshold to accept a match.
    # A score of 0.12 requires non-trivial text or context agreement beyond location
    # alone, preventing low-quality matches where a nearby unrelated span (e.g., a
    # reference dimension or section label) wins only on predicted-position proximity.
    # Unmatched anchors will be classified as "removed".
    MIN_MATCH_SCORE = 0.12
    MIN_WEAK_MATCH_SCORE = 0.24

    for total_score, char_no, span_key, candidate in edges:
        # Skip implausibly low-scoring matches — they indicate no real candidate
        if total_score < MIN_MATCH_SCORE:
            continue
        candidate_fp = parse_requirement(candidate.span.text)
        candidate_numerics = {v for v, _ in candidate_fp.numeric_tokens}
        has_primary_reason = any("primary=" in r or "Primary dimension matches" in r for r in candidate.reasons)
        if total_score < MIN_WEAK_MATCH_SCORE and not has_primary_reason and len(candidate_numerics) <= 1:
            continue
        # Wrong-copy guard: a global-fallback-only candidate must not steal a span
        # that already has a stronger local claimant.  If the target span key is in
        # span_keys_with_local_claimant and this edge is from the global fallback
        # pool, skip it — the local claimant will win on its own turn in the sorted
        # edge list.  This prevents removed anchors (no local candidate) from
        # displacing surviving anchors whose annotation happens to share the same
        # repeated text (Part 3-style wrong-copy failure).
        if candidate.from_global_fallback and span_key in span_keys_with_local_claimant:
            continue
        candidate_source_keys = tuple(sorted(candidate.source_span_keys or [span_key]))
        preferred_owner = preferred_owner_by_source_span_keys.get(candidate_source_keys)
        if preferred_owner is not None and preferred_owner != char_no:
            continue
        # Accept edge only if both char_no and span are available
        if char_no not in assigned_chars and span_key not in used_spans:
            candidate_source_keys_set = set(candidate.source_span_keys or [span_key])
            if candidate_source_keys_set & used_source_span_keys:
                continue
            matches[char_no] = Match(
                char_no=char_no,
                candidate=candidate,
                pred_center_b=None  # Can be populated by caller if needed
            )
            assigned_chars.add(char_no)
            used_spans.add(span_key)
            used_source_span_keys.update(candidate_source_keys_set)

    # Shared-span fallback: handle combined annotation spans that encode multiple
    # characteristics (e.g., "10 x 90°" for countersink depth=10 AND angle=90°).
    # For any anchor that remained unmatched, check if its primary numeric value
    # is present in a span that was already assigned to another anchor.  If yes,
    # allow the span to be reused — the annotation collectively describes both
    # characteristics and both should be classified (not marked "removed").
    for anchor in anchors:
        char_no = anchor.char_no
        if char_no in assigned_chars:
            continue  # Already matched

        candidates = candidates_by_anchor.get(char_no, [])
        anchor_fp = parse_requirement(anchor.requirement_raw)
        anchor_primary = max(
            (v for v, _ in anchor_fp.numeric_tokens), default=None
        )

        for candidate in candidates:
            if candidate.total_score < MIN_MATCH_SCORE:
                continue
            # Exclude candidates that were only found via the global page-wide
            # fallback.  A global-fallback-only anchor had no viable candidate
            # within the normal search radius, meaning the characteristic is
            # almost certainly removed (not merely moved).  Allowing it to
            # share an already-assigned span would wrongly classify it as
            # "unchanged" when it should be "removed".
            if candidate.from_global_fallback:
                continue
            span = candidate.span
            span_key = (
                span.block_id,
                span.line_id,
                span.span_id,
                span.bbox_pdf
            )
            # Only consider spans already used by another anchor (shared annotation)
            if span_key not in used_spans:
                continue
            # Allow reuse only when the anchor's primary value appears in the span
            if anchor_primary is None:
                continue
            span_fp = parse_requirement(span.text)
            span_numerics = {v for v, _ in span_fp.numeric_tokens}
            if anchor_primary not in span_numerics:
                continue
            # Primary value is confirmed in the span — allow shared match
            matches[char_no] = Match(
                char_no=char_no,
                candidate=candidate,
                pred_center_b=None
            )
            assigned_chars.add(char_no)
            break  # One shared match per anchor

    return matches


def refine_match_display_text(
    anchors: List[Anchor],
    matches: dict[int, Match],
) -> None:
    """Refine the display text of matched GroupedSpans to show only relevant sub-spans.

    When _group_candidate_spans() merges multiple annotations into one blob,
    the matched span's text includes text from neighbouring balloons.  This
    post-processing step selects only the source_span(s) that contain the
    anchor's primary numeric value, producing a clean display string.

    Mutates the Match objects' candidate.span.text in-place (for GroupedSpan
    instances only).  Regular TextSpan matches are left untouched.
    """
    anchor_by_char: dict[int, Anchor] = {a.char_no: a for a in anchors}

    for char_no, match in matches.items():
        span = match.candidate.span
        source_spans = getattr(span, "source_spans", None)
        if not source_spans or len(source_spans) <= 1:
            continue  # Nothing to refine — single span

        anchor = anchor_by_char.get(char_no)
        if anchor is None:
            continue

        # Skip refinement for GD&T feature control frames — the leading symbol
        # span (⌖∅, ⟂∅, ⌓, ⏥, ∠, etc.) has no numeric tokens and would be
        # stripped, breaking both display text and semantic comparison.
        _GDT_CONTROL_CHARS = set("⌖⌒⟂⊙⌓⏥∥∠")
        has_gdt = any(
            any(c in src.text for c in _GDT_CONTROL_CHARS)
            for src in source_spans
        )
        if has_gdt:
            continue  # Keep the full grouped text for GD&T FCFs

        anchor_fp = parse_requirement(anchor.requirement_raw)
        anchor_numerics = {v for v, _ in anchor_fp.numeric_tokens}
        anchor_primary = max(anchor_numerics) if anchor_numerics else None

        if anchor_primary is None:
            # Non-numeric anchor (e.g., notes) — keep full grouped text
            continue

        # Find source spans that contain ANY of the anchor's numeric values
        # (not just the primary) so that count tokens, symbols, and secondary
        # values (e.g., tolerances) on companion spans are preserved.
        relevant_spans: List[TextSpan] = []
        for src in source_spans:
            src_fp = parse_requirement(src.text)
            src_numerics = {v for v, _ in src_fp.numeric_tokens}
            if src_numerics & anchor_numerics:
                relevant_spans.append(src)

        if not relevant_spans:
            # Primary value not found in any individual sub-span — keep full text
            # (the value may only appear when spans are concatenated)
            continue

        # Sort relevant spans spatially (top-to-bottom, left-to-right)
        relevant_spans.sort(key=lambda s: (
            (s.bbox_pdf[1] + s.bbox_pdf[3]) / 2,
            s.bbox_pdf[0],
        ))

        # Replace the grouped span's display text with only the relevant pieces.
        # We mutate .text on the GroupedSpan dataclass; bbox stays as the full
        # group bbox so that snippet generation still captures the right region.
        refined_text = " ".join(s.text.strip() for s in relevant_spans if s.text.strip())
        if refined_text and refined_text != span.text:
            # GroupedSpan is frozen — replace the candidate's span with a new instance
            from delta_preservation.reconcile.match import GroupedSpan
            refined_span = GroupedSpan(
                text=refined_text,
                bbox_pdf=span.bbox_pdf,
                font_size=span.font_size,
                block_id=span.block_id,
                line_id=span.line_id,
                span_id=span.span_id,
                source_spans=span.source_spans,
            )
            match.candidate.span = refined_span
