"""
Candidate generation and matching module for cross-revision characteristic matching.

This module implements the core matching logic that finds potential Rev B candidates 
for each Rev A characteristic anchor. It uses spatial transformation to predict where
characteristics should appear in Rev B, then ranks candidates using multi-component
scoring that combines location, semantic similarity, and spatial context.

The matching process is critical for maintaining characteristic identity across 
drawing revisions, even when layout changes significantly.
"""

from typing import List, Tuple, Optional
from dataclasses import dataclass
import math
import numpy as np
import cv2

from delta_preservation.reconcile.anchors import Anchor
from delta_preservation.io.pdf import TextSpan
from delta_preservation.reconcile.normalize import parse_requirement
from delta_preservation.vision.alignment import Transform


@dataclass
class Candidate:
    """
    Represents a potential Rev B match for a Rev A characteristic anchor.
    
    Candidates are generated by spatial search around the predicted Rev B location
    and ranked using multi-component scoring. Each candidate represents a text span
    in Rev B that could potentially be the same characteristic as the Rev A anchor.
    
    Attributes:
        span: The Rev B text span containing potential requirement text
        total_score: Combined weighted score (0-1) indicating match confidence
        location_score: Distance-based proximity score (0-1, higher = closer)
        text_score: Semantic similarity score (0-1, higher = more similar content)
        context_score: Spatial context similarity score (0-1, higher = similar neighborhood)
        reasons: Human-readable explanations of score components for debugging/review
        
    Notes:
        - Total score combines all component scores with domain-specific weights
        - Reasons provide transparency for human review of matching decisions
        - Scores are normalized to [0,1] range for consistent interpretation
    """
    span: TextSpan
    total_score: float
    location_score: float
    text_score: float
    context_score: float
    reasons: List[str]


@dataclass
class Match:
    """
    Represents a confirmed assignment of a Rev A characteristic to a Rev B span.
    
    A Match is the result of the candidate ranking and assignment process, representing
    the system's best guess for where a Rev A characteristic appears in Rev B. This
    forms the basis for delta classification (unchanged/changed/removed).
    
    Attributes:
        char_no: Characteristic number from Rev A anchor (e.g., 1, 2, 17)
        candidate: The selected Candidate object containing the Rev B span and scores
        pred_center_b: Predicted center coordinates in Rev B (x, y) from spatial transform
        
    Notes:
        - Only one Match per char_no (enforced by assignment algorithm)
        - pred_center_b shows where the spatial transform predicted the characteristic
        - candidate.span contains the actual Rev B text that was matched
    """
    char_no: int
    candidate: Candidate
    pred_center_b: Optional[Tuple[float, float]] = None


def generate_candidates(
    anchor: Anchor,
    revB_spans: List[TextSpan],
    transform: Transform,
    top_k: int = 5
) -> List[Candidate]:
    """
    Generate and rank candidate matches for a Rev A anchor in Rev B coordinate space.
    
    This function implements the core characteristic matching algorithm:
    1. Apply homography transform to predict where anchor should appear in Rev B
    2. Search within a fixed radius for potential candidate text spans
    3. Score each candidate using location, semantic, and context similarity
    4. Return the top-K highest scoring candidates for assignment consideration
    
    The spatial transform handles layout changes between revisions, while multi-component
    scoring ensures robust matching even when text formatting or positioning varies.
    
    Args:
        anchor: Rev A anchor containing requirement text and spatial information
        revB_spans: Complete list of text spans extracted from Rev B PDF
        transform: Homography transformation matrix from Rev A to Rev B coordinates
        top_k: Maximum number of top-scoring candidates to return (default: 5)
        
    Returns:
        List of Candidate objects sorted by total_score in descending order.
        List may be shorter than top_k if fewer candidates found within search radius.
        
    Notes:
        - Uses 144 PDF point (~2 inch) search radius to handle layout variations
        - Prioritizes requirement text bbox over balloon center for spatial prediction
        - Handles cases where anchor has no requirement text bbox (uses balloon fallback)
        - All candidates include detailed scoring breakdown for transparency
    """
    # Define search radius to handle layout variations between revisions
    # 144 PDF points ≈ 2 inches at 72 DPI - generous enough for significant layout changes
    SEARCH_RADIUS = 144.0
    
    # Determine the Rev A coordinate to transform (prefer requirement text over balloon)
    # Requirement text location is more precise than balloon center for matching
    if anchor.req_bbox is not None:
        x0, y0, x1, y1 = anchor.req_bbox
        center_a = np.array([[(x0 + x1) / 2, (y0 + y1) / 2]], dtype=np.float32)
    else:
        # Fall back to balloon center when requirement text location is unknown
        center_a = np.array([[(anchor.balloon_bbox[0] + anchor.balloon_bbox[2]) / 2,
                             (anchor.balloon_bbox[1] + anchor.balloon_bbox[3]) / 2]], dtype=np.float32)
    
    # Apply homography transformation to predict Rev B location
    center_a = center_a.reshape(-1, 1, 2)
    center_b = cv2.perspectiveTransform(center_a, transform.H)[0][0]
    pred_x, pred_y = center_b
    
    # Build candidate pool from spans within search radius
    # Pre-filter to reduce computational cost of detailed scoring
    candidate_pool = []
    for span in revB_spans:
        sx0, sy0, sx1, sy1 = span.bbox_pdf
        span_cx = (sx0 + sx1) / 2
        span_cy = (sy0 + sy1) / 2
        dist = math.sqrt((span_cx - pred_x)**2 + (span_cy - pred_y)**2)
        
        if dist <= SEARCH_RADIUS:
            candidate_pool.append((span, dist, span_cx, span_cy))
    
    # Apply detailed multi-component scoring to each candidate
    # This is the most computationally intensive part but crucial for accuracy
    candidates = []
    for span, dist, cx, cy in candidate_pool:
        candidate = score_candidate(
            anchor, span, dist, SEARCH_RADIUS,
            revB_spans, cx, cy
        )
        candidates.append(candidate)
    
    # Return top-K candidates sorted by total score (best matches first)
    # This ranking determines which candidates get considered for assignment
    candidates.sort(key=lambda c: c.total_score, reverse=True)
    return candidates[:top_k]


def score_candidate(
    anchor: Anchor,
    span: TextSpan,
    dist: float,
    radius: float,
    all_spans: List[TextSpan],
    span_cx: float,
    span_cy: float
) -> Candidate:
    """
    Compute multi-component similarity score for a candidate Rev B span.
    
    This function implements the core matching intelligence by analyzing three
    complementary similarity signals:
    1. Location: Spatial proximity to the predicted Rev B location
    2. Text: Semantic similarity of requirement content (symbols, numbers, patterns)
    3. Context: Similarity of nearby text spans (spatial neighborhood fingerprint)
    
    The scoring emphasizes numeric value matching as the primary discriminator,
    since dimension values are the most reliable identifier of engineering
    characteristics. Location provides spatial validation, while context helps
    disambiguate when multiple similar annotations exist.
    
    Args:
        anchor: Rev A anchor containing original requirement text and context
        span: Candidate Rev B text span being evaluated for matching
        dist: Distance in PDF points from span center to predicted Rev B center
        radius: Search radius used to normalize distance scores
        all_spans: Complete list of Rev B spans for context analysis
        span_cx: X-coordinate of candidate span center (for context search)
        span_cy: Y-coordinate of candidate span center (for context search)
        
    Returns:
        Candidate object with detailed scoring breakdown and human-readable
        explanations for transparency in matching decisions.
        
    Notes:
        - Numeric matching receives highest weight (50%) in final score
        - Primary value mismatches incur significant penalties
        - Context similarity uses Jaccard index of neighboring text tokens
        - All component scores normalized to [0,1] for consistent weighting
    """
    reasons = []
    
    # (1) Location score - distance-based, normalized to [0, 1]
    location_score = 1.0 - min(dist / radius, 1.0)
    if location_score > 0:
        dist_mm = dist * 25.4 / 72.0  # Convert points to mm
        reasons.append(f"within {dist_mm:.1f} mm of predicted location")
    
    # (2) Text score - semantic matching using parsed requirement fingerprints
    # Parse both texts to extract symbols, numbers, patterns for structured comparison
    anchor_fp = parse_requirement(anchor.requirement_raw)
    span_fp = parse_requirement(span.text)
    
    # Compare engineering symbols (e.g., Ø for diameter, R for radius, ± for tolerance)
    anchor_symbols = set(anchor_fp.symbol_tokens)
    span_symbols = set(span_fp.symbol_tokens)
    symbol_match = len(anchor_symbols & span_symbols) / max(len(anchor_symbols), 1) if anchor_symbols else 0.0
    
    # Compare count patterns (e.g., 2X, 4X, 6X)
    anchor_counts = set(anchor_fp.count_tokens)
    span_counts = set(span_fp.count_tokens)
    has_count_pattern = bool(anchor_counts and span_counts)
    count_exact_match = anchor_counts == span_counts if anchor_counts else True
    
    # Compare numeric values - THIS IS THE KEY DISCRIMINATOR
    # Extract the primary numeric value (usually the dimension value, not tolerance)
    anchor_numerics = set(val for val, _ in anchor_fp.numeric_tokens)
    span_numerics = set(val for val, _ in span_fp.numeric_tokens)
    
    # Identify the "primary" numeric value (largest value, likely the dimension)
    anchor_primary = max(anchor_numerics) if anchor_numerics else None
    span_primary = max(span_numerics) if span_numerics else None
    
    # Compute numeric overlap
    if anchor_numerics:
        numeric_overlap = len(anchor_numerics & span_numerics) / len(anchor_numerics)
    else:
        numeric_overlap = 1.0 if not span_numerics else 0.0
    
    # Check if primary value matches exactly
    primary_value_match = (
        anchor_primary is not None and 
        span_primary is not None and 
        anchor_primary == span_primary
    )
    
    # Strong penalty if primary values exist but don't match
    # This prevents matching "110" to "120" even if they're close in location
    primary_mismatch_penalty = 0.0
    if anchor_primary is not None and span_numerics:
        if anchor_primary not in span_numerics:
            # The anchor's primary value is NOT in the span - strong penalty
            primary_mismatch_penalty = 0.4
            reasons.append(f"primary value {anchor_primary} not found in span")
    
    # Compare pattern class (hole, dimension, note, etc.)
    class_match = 1.0 if anchor_fp.pattern_class == span_fp.pattern_class else 0.0
    
    # Weighted combination for text score
    # Numeric matching is now the dominant factor
    text_score = (
        0.15 * symbol_match +
        0.15 * (1.0 if has_count_pattern else 0.0) +
        0.50 * numeric_overlap +  # Heavily weight numeric match
        0.10 * class_match +
        0.10 * (1.0 if primary_value_match else 0.0)  # Bonus for exact primary match
    )
    
    matched_parts = []
    if symbol_match > 0:
        matched_parts.append(f"symbols: {anchor_symbols & span_symbols}")
    if has_count_pattern:
        matched_parts.append(f"counts: {anchor_counts} vs {span_counts}")
    if numeric_overlap > 0:
        matched_parts.append(f"numerics: {int(numeric_overlap*100)}%")
    if primary_value_match:
        matched_parts.append(f"primary={anchor_primary}")
    if matched_parts:
        reasons.append(f"matched: {', '.join(matched_parts)}")
    
    # (3) Context score - Jaccard of neighboring spans
    CONTEXT_WINDOW = 50.0  # Points
    
    # Get anchor context tokens
    anchor_context_tokens = set()
    for ctx_span in anchor.local_context:
        ctx_parsed = parse_requirement(ctx_span.text)
        anchor_context_tokens.update(ctx_parsed.norm_text.split())
    
    # Get candidate context tokens
    candidate_context_tokens = set()
    for other_span in all_spans:
        if other_span.block_id != span.block_id:
            continue
        ox0, oy0, ox1, oy1 = other_span.bbox_pdf
        other_cx = (ox0 + ox1) / 2
        other_cy = (oy0 + oy1) / 2
        other_dist = math.sqrt((other_cx - span_cx)**2 + (other_cy - span_cy)**2)
        
        if other_dist <= CONTEXT_WINDOW and other_dist > 0:
            other_parsed = parse_requirement(other_span.text)
            candidate_context_tokens.update(other_parsed.norm_text.split())
    
    # Jaccard similarity
    if anchor_context_tokens or candidate_context_tokens:
        intersection = len(anchor_context_tokens & candidate_context_tokens)
        union = len(anchor_context_tokens | candidate_context_tokens)
        context_score = intersection / union if union > 0 else 0.0
        if context_score > 0:
            reasons.append(f"context similarity: {context_score:.2f}")
    else:
        context_score = 0.0
    
    # Combine scores with rebalanced weights
    # Text/numeric matching is now more important than location
    LOCATION_WEIGHT = 0.35
    TEXT_WEIGHT = 0.50
    CONTEXT_WEIGHT = 0.15
    
    total_score = (
        LOCATION_WEIGHT * location_score +
        TEXT_WEIGHT * text_score +
        CONTEXT_WEIGHT * context_score -
        primary_mismatch_penalty  # Apply penalty for wrong primary value
    )
    
    # Ensure score doesn't go negative
    total_score = max(0.0, total_score)
    
    return Candidate(
        span=span,
        total_score=total_score,
        location_score=location_score,
        text_score=text_score,
        context_score=context_score,
        reasons=reasons
    )


def assign_matches(
    anchors: List[Anchor],
    candidates_by_anchor: dict[int, List[Candidate]]
) -> dict[int, Match]:
    """Greedily assign anchors to Rev B spans using a global matching strategy.
    
    This function implements a greedy bipartite matching algorithm that ensures:
    1. Each characteristic (char_no) is assigned at most once
    2. Each Rev B span is matched to at most one characteristic
    
    The algorithm flattens all candidate edges, sorts by score, and greedily
    accepts edges that don't conflict with previous assignments.
    
    Args:
        anchors: List of Rev A anchors with characteristic numbers
        candidates_by_anchor: Dict mapping char_no to list of candidates
        
    Returns:
        Dict mapping assigned char_no to its Match object
    """
    # Build list of all edges: (total_score, char_no, span_key, candidate)
    edges = []
    for anchor in anchors:
        char_no = anchor.char_no
        candidates = candidates_by_anchor.get(char_no, [])
        
        for candidate in candidates:
            # Create unique span key using TextSpan attributes
            span = candidate.span
            span_key = (
                span.block_id,
                span.line_id,
                span.span_id,
                span.bbox_pdf
            )
            
            edges.append((
                candidate.total_score,
                char_no,
                span_key,
                candidate
            ))
    
    # Sort edges by total_score descending
    edges.sort(key=lambda e: e[0], reverse=True)
    
    # Greedy assignment
    assigned_chars = set()
    used_spans = set()
    matches = {}
    
    for total_score, char_no, span_key, candidate in edges:
        # Accept edge only if both char_no and span are available
        if char_no not in assigned_chars and span_key not in used_spans:
            matches[char_no] = Match(
                char_no=char_no,
                candidate=candidate,
                pred_center_b=None  # Can be populated by caller if needed
            )
            assigned_chars.add(char_no)
            used_spans.add(span_key)
    
    return matches
