[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:uvicorn]
directory=/app
command=/app/.venv/bin/uvicorn shop.app:app --host 0.0.0.0 --port 8000
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=10

[program:huey_worker]
directory=/app
command=/app/.venv/bin/huey_consumer.py shop.tasks.huey --workers=1 --worker-type=thread
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=20
